import type { Config } from "tailwindcss"
import forms from "@tailwindcss/forms"
import containerQueries from "@tailwindcss/container-queries"

const config: Config = {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#fcf9f8",
        "surface-bright": "#fcf9f8",
        "surface-dim": "#dcd9d9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0eded",
        "surface-container-high": "#eae7e7",
        "surface-container-highest": "#e5e2e1",
        "surface-variant": "#e5e2e1",
        "surface-tint": "#735c00",
        "surface-glass": "rgba(255, 255, 255, 0.7)",
        "on-surface": "#1b1c1c",
        "on-surface-variant": "#4d4635",
        "inverse-surface": "#303030",
        "inverse-on-surface": "#f3f0ef",
        "outline": "#7f7663",
        "outline-variant": "#d0c5af",
        "primary": "#735c00",
        "on-primary": "#ffffff",
        "primary-container": "#d4af37",
        "on-primary-container": "#554300",
        "primary-fixed": "#ffe088",
        "primary-fixed-dim": "#e9c349",
        "on-primary-fixed": "#241a00",
        "on-primary-fixed-variant": "#574500",
        "inverse-primary": "#e9c349",
        "secondary": "#655497",
        "on-secondary": "#ffffff",
        "secondary-container": "#c7b3ff",
        "on-secondary-container": "#534284",
        "secondary-fixed": "#e8ddff",
        "secondary-fixed-dim": "#cebdff",
        "on-secondary-fixed": "#200b50",
        "on-secondary-fixed-variant": "#4c3c7e",
        "tertiary": "#815152",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#dfa4a4",
        "on-tertiary-container": "#64393a",
        "tertiary-fixed": "#ffdad9",
        "tertiary-fixed-dim": "#f5b7b7",
        "on-tertiary-fixed": "#331012",
        "on-tertiary-fixed-variant": "#663a3b",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "background": "#fcf9f8",
        "on-background": "#1b1c1c",
        "champagne-gold": "#D4AF37",
        "soft-amethyst": "#8E7CC3",
        "faded-rose": "#E5A9A9",
        "canvas-white": "#FAF9F6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "64px",
        "container-max": "1440px",
      },
      maxWidth: {
        "container-max": "1440px",
      },
      fontFamily: {
        "display-lg": ["Playfair Display", "serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "caption": ["Inter", "sans-serif"],
        "serif": ["Playfair Display", "serif"],
        "sans": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "caption": ["12px", { lineHeight: "16px", fontWeight: "400" }],
      },
      boxShadow: {
        "gold-glow": "0 20px 40px -15px rgba(212, 175, 55, 0.25)",
        "ambient": "0 8px 32px rgba(115, 92, 0, 0.08)",
      },
      keyframes: {
        "fade-up": {
          "0%": { opacity: "0", transform: "translateY(12px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "float-soft": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-8px)" },
        },
      },
      animation: {
        "fade-up": "fade-up 0.6s ease-out both",
        "float-soft": "float-soft 4s ease-in-out infinite",
      },
    },
  },
  plugins: [forms, containerQueries],
}

export default config
